language: python
python:
  - 2.7
  - 3.3
addons:
  postgresql: "9.2"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - DATABASE_URI=postgresql://localhost/travis_ci_test
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install coveralls
script:
  - coverage run --source=flask_dance runtests.py
after_success:
  - coveralls
