language: python
python:
  - 2.7
  - 3.3
addons:
  postgresql: "9.2"
env:
  - DATABASE_URI=postgresql://localhost/travis_ci_test
  - DATABASE_URI=sqlite://
before_script:
  - if [[ $DATABASE_URI == postgresql* ]]; then psql -c 'create database travis_ci_test;' -U postgres; fi
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - if [[ $DATABASE_URI == postgresql* ]]; then pip install psycopg2; fi
  - pip install coveralls
script:
  - coverage run --source=flask_dance runtests.py
after_success:
  - coveralls
